### ISSUE TITLE
Error message when script runs "OPERATIONS_ERROR"

### ISSUE THREAD

**Issue by riramos** [SecuProject/ADenum#2]
Hello, i tried to run the script, but I received this error message:

[-] OPERATIONS_ERROR: {'msgtype': 100, 'msgid': 2, 'result': 1, 'desc': 'Operations error', 'ctrls': [], 'info': '000004DC: LdapErr: DSID-0C090A7D, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v3839'}

Please, could you help me.

Regards

**Comment by SecuProject** [comment]
Hi riramos,

I will investigate the issue and the return to you.

Regards

**Comment by archidote** [comment]
Hey, I have the same problem as Riramos. 

I'm running windows server 2022 datacenter edition in a pentestlab. 

![image](https://user-images.githubusercontent.com/38756128/145594595-11d3dce5-2601-4b1a-b977-6d9ff552c183.png)


Did you find the issue ? 

regards,

**Comment by SecuProject** [comment]
I have done some research and I think that I have found the solution. 

In the documentation of the library `python-ldap` they explain the following: 

```
When searching from the domain level, MS AD returns referrals (search continuations) for some objects to indicate to the client where to look for these objects. Client-chasing of referrals is a broken concept, since LDAPv3 does not specify which credentials to use when chasing the referral. Windows clients are supposed to simply use their Windows credentials, but this does not work in general when chasing referrals received from and pointing to arbitrary LDAP servers."
```
Source: https://www.python-ldap.org/en/python-ldap-3.3.0/faq.html

The solution they are providing to solve this issue is simply to switch this behavior off:

```python
l.set_option(ldap.OPT_REFERRALS,0)
```

Regards,
