### ISSUE TITLE
IndentationError: unexpected indent

### ISSUE THREAD

**Issue by tfmarques23** [SecuProject/ADenum#3]
after run and install all requirements, when i run the script the system give error:
![image](https://user-images.githubusercontent.com/92591638/142252390-92e0a299-3d3c-4faf-8cb5-9d78ef9dd02d.png)

**Comment by tfmarques23** [comment]
Add import logging firts line and remove space 2line and works

**Comment by SecuProject** [comment]
Hi tfmarques23,

Thank you for pointing out the issues. It is now fix

Regards
