### ISSUE TITLE
Problem during installation (kali linux)

### ISSUE THREAD

**Issue by archidote** [SecuProject/ADenum#4]
Hello, this morning I tried to install your tool on my kalilinux (version 2021.4), but I got some errors with the following depedancie : 

- python-ldap

So I found a solution : 

link : https://www.python-ldap.org/en/python-ldap-3.3.0/installing.html#installing-from-source

```
apt-get install build-essential python3-dev python2.7-dev libldap2-dev libsasl2-dev slapd ldap-utils tox lcov valgrind

```

afterthat : 

```
pip3 install -r Requirement.txt
``` 

<b>On ubuntu, your little tutorial work perfectly, so maybe update your README for kali linux distro. </b>

Best regards,

**Comment by SecuProject** [comment]
Hi archidote,

Thanks for reporting the issue. 
I just tested the installation process on **Kali Linux** (version **2021.4**) and the package `python-dev` is now called `python2-dev`.
Btw, I have also updated the name of the file `Requirement.txt`  to `requirements.txt` which is the recommended name for the requirements file. 

Best regards
